version: "3.9"

services:

  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  resume-worker:
    build: .
    command: node src/workers/resumeWorker.js
    env_file:
      - ${ENV_FILE}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  resume-parse-worker:
    build: .
    command: node src/workers/resumeParseWorker.js
    env_file:
      - ${ENV_FILE}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    user: "0"
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./monitoring/promtail.yml:/etc/promtail/promtail.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  postgres-data:
  grafana-data:
  prometheus-data:
  loki-data: